print('hello world')
print('this is first program in python')
print('Hassan is a bad boy')
print('hi \n how are you')

name = 'tim'
print(name)
print(name.upper())
print(name.lower())
print(name[0])
print(name[1])
print(name.isupper())
print(name.islower() )
print(len(name))
print(name.index('m'))
print(name.replace('m','i'))